server:
  port: 9094

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: FOOD-CATALOGE-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/foodcatalogedb
    username: edwar
    password: edwar123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
